import os

with open("/Users/riyasudeen/Documents/clien web/xerox/src/main.js") as f:
    js = f.read()

# Make sure all img tags generated by JS have loading="lazy" decoding="async" width="600" height="400"
js = js.replace('alt="${p.title}" loading="lazy" decoding="async" />', 'alt="${p.title}" loading="lazy" decoding="async" width="600" height="400" />')

with open("/Users/riyasudeen/Documents/clien web/xerox/src/main.js", "w") as f:
    f.write(js)

print("Updated main.js image tags with width/height attributes for SEO performance")
